"""

@author: Ying Meng (y(dot)meng201011(at)gmail(dot)com)
"""

from enum import Enum

class IdealModelEvalHeaders(Enum):
    NUM_OF_WEAK_DEFENSES = 'Num_of_Weak_Defenses'
    TOP_K = 'TopK'
    BOTTOM_K = 'BottomK'
    RANDK_R0 = 'RandK_R0'
    RANDK_R1 = 'RandK_R1'
    RANDK_R2 = 'RandK_R2'
    RANDK_R3 = 'RandK_R3'
    RANDK_R4 = 'RandK_R4'
    RANDK_R5 = 'RandK_R5'
    RANDK_R6 = 'RandK_R6'
    RANDK_R7 = 'RandK_R7'
    RANDK_R8 = 'RandK_R8'
    RANDK_R9 = 'RandK_R9'
    RANDK_R10 = 'RandK_R10'
    RANDK_R11 = 'RandK_R11'
    RANDK_R12 = 'RandK_R12'
    RANDK_R13 = 'RandK_R13'
    RANDK_R14 = 'RandK_R14'
    RANDK_R15 = 'RandK_R15'
    RANDK_R16 = 'RandK_R16'
    RANDK_R17 = 'RandK_R17'
    RANDK_R18 = 'RandK_R18'
    RANDK_R19 = 'RandK_R19'
    RANDK_R20 = 'RandK_R20'
    RANDK_R21 = 'RandK_R21'
    RANDK_R22 = 'RandK_R22'
    RANDK_R23 = 'RandK_R23'
    RANDK_R24 = 'RandK_R24'
    RANDK_R25 = 'RandK_R25'
    RANDK_R26 = 'RandK_R26'
    RANDK_R27 = 'RandK_R27'
    RANDK_R28 = 'RandK_R28'
    RANDK_R29 = 'RandK_R29'
    RANDK_AVG = 'RandK_Avg'
    RANDK_MEAN = 'RandK_Mean'
    RANDK_UPPERBOUND = 'RandK_UB'
    RANDK_LOWERBOUND = 'RandK_LB'
    GAP = 'Gap'
