model:
  type: resnet200
dataset: imagenet
aug: fa_reduced_imagenet
cutout: 0
batch: 256
epoch: 270
lr: 0.05
lr_schedule:
  type: 'resnet'
  warmup:
    multiplier: 2
    epoch: 3
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
  clip: 0
